### ISSUE TITLE
How to run multiple Clinical trial Studies within a single instance 

### ISSUE THREAD

**Issue by vagarwal77** [clinicedc/edc#7]
We are interested to setup edc for multiple studies - 
What i would like to do is -

1. setup and deploy edc modules as a service
2. Build study A, study B, study C of different Oncology on the same deployment without any code changes. We can import different study ODM files or update config files
3. Current commercialized EDC like Medidata use XML ODM for study configuration setup, Veeva use json config to build study. I am looking for a similar solution. Based upon your above comments, looks like, every time we need a new study, we need to build new Django models and need to deploy separately, which is kind of against todays SaaS model.

I may understood readme or your comments incorrectly so, please suggest or i am in EST time zone and would love to hop on a call with you.

**Comment by erikvw** [comment]
Thanks for this comment and apologies for not replying earlier. 

I do like the idea of generating the initial version of the Django model classes based on simple config files. Writing the initial model, form and admin classes is tedious boilerplate coding. We can usually limit the boilerplate code by parsing WORD docs with a snippet of python code. But there is some benefit to going through the model classes carefully. Our developers are usually part of the research team and have much to offer in translating the original data collection tools (a set of CRFs developed on WORD) to a set of eCRFs that flow efficiently and make use of being deployed through a data-aware system. 

My objective is also to fit the software to the trial and not fit the trial to the software.

Our team has mostly supported complex multisite trials so using a single config file to describe all aspects of the eligibility criteria, randomisation scheme, data collection schedule, CRFs, the complex validation between data points, reporting requirements, monitoring strategies, etc is not practical. Python is easy to read and write and we isolate functionality into manageable parts. Also, much is learned after the trial starts when what seemed fine on paper meets the reality on the ground. Python code is easy to modify and git tracks all the changes nicely.

With the clinicedc approach, we build business rules and processes into the system as we learn more about the ongoing trial. The investigators don’t always have battle tested protocols to work from. Also, by absorbing as much of the trial logic into the EDC as possible, we protect the trial from high staff turnover and drifting understanding of the protocol.  We learn as we go. If you look at some of the more recent repositories on the README you'll see the repo changes well after the trial starts.
